version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    ports:
      - "5175:8080"  # Expose the Vite default port
    networks:
      - todo_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"  # Adjust based on your backend config
    depends_on:
      - mysql  # Ensure backend starts after MySQL
    networks:
      - todo_network
    environment:
      DATABASE_URL: "mysql://myuser:mypassword@mysql:3306/tododb"  # Change 'mydb' to 'tododb'


  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tododb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mysql_data:
