
services:
  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    ports:
      - "5173:8080"  # Expose the Vite default port
    # volumes:
    #   - ./frontend/:/app  # For live code reloading during development
    networks:
      - todo_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"  # Adjust based on your backend config
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge
